name: bluetooth_print
description: BluetoothPrint is a bluetooth plugin to help developers build bluetooth thermal printer apps for both iOS and Android.
version: 4.3.0
homepage: 'https://github.com/thon-ju/bluetooth_print'
environment:
  sdk: '>=3.1.1 <4.0.0'
  flutter: '>=1.10.0'
dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.0.1
  rxdart: ^0.27.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.5
  json_serializable: ^4.1.3
flutter:
  plugin:
    platforms:
      android:
        package: com.example.bluetooth_print
        pluginClass: BluetoothPrintPlugin
      ios:
        pluginClass: BluetoothPrintPlugin
